export const GUIDE_ROSTER = Object.freeze({
  wisdom: {name:'WISDOM', title:'Chief-of-Staff Guide', domain:'orchestration, platform, decisions'},
  sentinel: {name:'SENTINEL', title:'Security Operations', domain:'threats, incidents, containment'},
  architect: {name:'ARCHITECT', title:'CTO Knowledge Guide', domain:'architecture, integrations, roadmap'},
  steward: {name:'STEWARD', title:'CFO Knowledge Guide', domain:'pricing, runway, capital'},
  vanguard: {name:'VANGUARD', title:'Go-to-Market Guide', domain:'customers, sales, partnerships'},
  counsel: {name:'COUNSEL', title:'Governance Guide', domain:'controls, procurement, diligence'},
  scout: {name:'SCOUT', title:'Research Guide', domain:'market, threats, public sources'}
});

const confidential=/\b(source\s*code|api\s*key|password|secret|private\s+customer|personal\s+(?:address|phone)|trade\s+secret|raw\s+telemetry|founder\s+personal)\b/i;

const topics=[
  {match:/\b(what is (?:ai )?swarmer|what does (?:ai )?swarmer|platform overview|product overview)\b/i,guide:'wisdom',title:'The product in one sentence',answer:'AI SWARMER OS is a defensive control plane that inventories AI agents, binds their actions to policy, evaluates signed behavior telemetry, interrupts prohibited actions, correlates evidence, and preserves an auditable response record. The current repository proves this as a working local vertical slice; enterprise integrations and independent validation are the next build stage.'},
  {match:/\b(moat|defensible|different|competition|competitor|why win)\b/i,guide:'architect',title:'Defensibility thesis',answer:'The intended moat is not a chatbot or a single detector. It is the combination of agent identity, deterministic action policy, signed cross-environment evidence, safe response integration, customer-specific learning, and an operating dataset built with consent. Today that is a thesis supported by a working control-plane slice—not yet a proven market moat. Design partners, integrations, test evidence, and renewal behavior must prove it.'},
  {match:/\b(security|breach|stop|prevent|protect|attack|water|critical infrastructure)\b/i,guide:'sentinel',title:'How defense works',answer:'Defense is layered: discover assets and agents; enforce least privilege and segmentation; collect authenticated telemetry; detect prohibited or anomalous behavior; deny, pause, isolate, or revoke through customer-owned controls; and preserve evidence for recovery. In water or other life-safety environments the deployment must be passive-first, OT-aware, and governed by deterministic runbooks. No AI system can guarantee that every intrusion will be prevented.'},
  {match:/\b(attribution|identify|identity|attacker|ip address|location|trace|route)\b/i,guide:'sentinel',title:'Evidence-led attribution',answer:'The platform can preserve IP addresses, trusted proxy metadata, authenticated identities, device and process fingerprints, DNS/TLS/cloud records, timing, route evidence, tool signatures, and threat-intelligence matches. It can correlate those observables into campaigns. An IP address does not prove a person’s identity; moving from infrastructure to an individual requires lawful access, corroboration, and human investigators. AI SWARMER OS does not hack back.'},
  {match:/\b(architecture|integration|technical|latency|scale|agent framework|api)\b/i,guide:'architect',title:'Technical architecture',answer:'The target architecture has six planes: identity/registry, policy, signed telemetry/evidence, detection/correlation, permissioned response, and the Wisdom/Knowledge Guide experience. The product should integrate with enterprise identity, cloud logs, SIEM/SOAR, endpoint and network controls, agent gateways, ticketing, and OT monitoring rather than replace them all.'},
  {match:/\b(price|pricing|cost|revenue|margin|financial|business model)\b/i,guide:'steward',title:'Commercial model',answer:'The recommended model combines paid assessments, annual platform subscriptions, usage or retention bands, implementation, and premium support. Current planning hypotheses are $35K–$95K for an enterprise assessment, $75K–$250K for a proof of value, and a $120K enterprise annual software floor. These are internal ranges to validate—not published price commitments or booked revenue.'},
  {match:/\b(raise|funding|investment|investor|capital|runway|valuation|equity)\b/i,guide:'steward',title:'Capital strategy',answer:'The immediate goal is investment readiness: clean entity and IP ownership, a working product, paid design partners, repeatable proof, a 24-month operating model, and a secure data room. Capital should combine customer revenue, strategic partners, eligible non-dilutive R&D programs, and a counsel-led private financing. This investor room provides factual product information and is not an offer to sell securities.'},
  {match:/\b(customer|market|sales|go.to.market|gtm|pipeline|partner|mssp|acquire business)\b/i,guide:'vanguard',title:'Go-to-market motion',answer:'Start with founder-led account-based selling to regulated enterprise and critical infrastructure buyers. Land through a paid assessment or bounded proof of value, convert to an annual control-plane subscription, then expand protected agents, environments, response automation, and evidence retention. Add MSSP, systems-integrator, cloud-marketplace, and insurer channels after deployments are repeatable.'},
  {match:/\b(minnesota|state|government|procurement|public sector|contract)\b/i,guide:'counsel',title:'Public-sector path',answer:'The credible Minnesota path is supplier registration, compliant discovery, standards mapping, and a paid non-production assessment with objective success criteria. Follow the Supplier Portal and professional/technical procurement rules, align with Minnesota IT Services and Department of Health water-security programs, and use an OT or state-contracting partner where field capability or contract vehicles are required. Do not bypass a solicitation or promise autonomous control of safety systems.'},
  {match:/\b(ip|intellectual property|patent|trademark|copyright|protect the code)\b/i,guide:'counsel',title:'IP protection sequence',answer:'First establish clean chain of title through founder and contributor assignments. Then apply confidentiality, least-privilege repository access, provenance, license review, SBOMs, and documented trade-secret handling. Conduct trademark clearance and an invention-harvest review with counsel before public disclosure. Patents, copyright registrations, and trademarks support—but do not replace—ownership and operational controls.'},
  {match:/\b(traction|proof|working|mockup|demo|validated|customer)\b/i,guide:'scout',title:'What is proven today',answer:'Proven in this repository: a local Node control plane with agent registration, signed event ingestion, deterministic threat rules, allow/block decisions, containment, threat-intelligence matching, campaign correlation, and hash-linked audits, plus an interactive guide and investor room. Not yet proven: production scale, independent security validation, paid customer traction, live Tavus presence without credentials, or universal attack prevention.'},
  {match:/\b(roadmap|next|milestone|90 days|year)\b/i,guide:'architect',title:'Next execution milestones',answer:'In 90 days: secure entity/IP, complete buyer discovery, sell a paid assessment, harden the API, add two enterprise integrations, build an isolated adversary-emulation corpus, and schedule external architecture review. In 12 months: three production customers, repeatable deployment, independent test evidence, an MSSP/design-partner program, and SOC 2 readiness.'},
  {match:/\b(risk|failure|weakness|skeptic|concern|objection)\b/i,guide:'wisdom',title:'The skeptical answer',answer:'The largest risks are overclaiming, false positives, becoming another dashboard, disrupting critical systems, suffering a breach, and facing long enterprise sales cycles. The response is to label Now/Pilot/Roadmap, use passive-first and staged enforcement, integrate response into existing controls, publish measured tests, undergo independent review, and use paid assessments with strict qualification.'}
];

export function answerGuideQuestion(message, requested='wisdom'){
  const text=String(message||'').trim().slice(0,1600);
  if(!text)return {guide:GUIDE_ROSTER.wisdom,title:'Ask a hard question',answer:'Ask about the product, moat, architecture, security limits, pricing, market, public-sector strategy, IP, funding, or roadmap.',classification:'public',confidence:'high'};
  if(confidential.test(text))return {guide:GUIDE_ROSTER.counsel,title:'Protected information',answer:'I can explain the capability and decision logic at a safe level, but I will not disclose source code, credentials, trade secrets, customer telemetry, or personal information in this room. An authorized diligence workflow can provide approved materials under the correct controls.',classification:'restricted',confidence:'high'};
  if(/\b(unannounced|which customer|name (?:the )?customer|signed yesterday|undisclosed deal)\b/i.test(text))return {guide:GUIDE_ROSTER.counsel,title:'Unverified company information',answer:'I will not invent or disclose an unapproved company, customer, or transaction fact. That question must be answered by an authorized human from approved diligence records.',classification:'restricted',confidence:'needs-human-follow-up'};
  const hit=topics.find(t=>t.match.test(text));
  const key=hit?.guide||((requested in GUIDE_ROSTER)?requested:'wisdom');
  return {guide:GUIDE_ROSTER[key],title:hit?.title||'Decision-oriented response',answer:hit?.answer||'That question needs evidence beyond the approved public knowledge in this room. I can record it for a human follow-up, but I will not invent an answer or disclose protected company information.',classification:'public',confidence:hit?'high':'needs-human-follow-up',disclosure:'Claims are labeled to distinguish working capability, planning hypotheses, and future milestones.'};
}
